#!/usr/bin/env sh

cat jsbn.js random.js hash.js rsa.js aes.js api.js rsa-asn.js rsa-rfc2313.js > cryptico.js

java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js cryptico.js --js_output_file cryptico.min.js
